module.exports = {
  moduleFileExtensions: ['js', 'json', 'ts'],
  rootDir: '.',
  testRegex: '.*\\.spec\\.ts$',
  transform: {
    '^.+\\.(t|j)s$': 'ts-jest',
  },
  collectCoverageFrom: ['**/*.(t|j)s'],
  coverageDirectory: './coverage',
  testEnvironment: 'node',
  moduleNameMapper: {
    '^@/applications/(.*)$': '<rootDir>/src/applications/$1',
    '^@/infrastructure/(.*)$': '<rootDir>/src/infrastructure/$1',
    '^@/domains/(.*)$': '<rootDir>/src/domains/$1',
    '^@/mall/(.*)$': '<rootDir>/src/applications/mall/$1',
    '^@/prisma/(.*)$': '<rootDir>/src/infrastructure/prisma/$1',
    '^@/minio/(.*)$': '<rootDir>/src/infrastructure/minio/$1',
    '^@/redis/(.*)$': '<rootDir>/src/infrastructure/redis/$1',
    '^@/icon-assets/(.*)$': '<rootDir>/src/infrastructure/icon-assets/$1',
    '^@/auth/(.*)$': '<rootDir>/src/domains/auth/$1',
    '^@/users/(.*)$': '<rootDir>/src/domains/users/$1',
    '^@/roles/(.*)$': '<rootDir>/src/domains/roles/$1',
    '^@/menus/(.*)$': '<rootDir>/src/domains/menus/$1',
    '^@/units/(.*)$': '<rootDir>/src/domains/units/$1',
    '^@/categories/(.*)$': '<rootDir>/src/domains/categories/$1',
    '^@/brands/(.*)$': '<rootDir>/src/domains/brands/$1',
    '^@/banners/(.*)$': '<rootDir>/src/domains/banners/$1',
    '^@/warehouses/(.*)$': '<rootDir>/src/domains/warehouses/$1',
    '^@/suppliers/(.*)$': '<rootDir>/src/domains/suppliers/$1',
    '^@/customers/(.*)$': '<rootDir>/src/domains/customers/$1',
    '^@/products/(.*)$': '<rootDir>/src/domains/products/$1',
    '^@/inventories/(.*)$': '<rootDir>/src/domains/inventories/$1',
    '^@/purchases/(.*)$': '<rootDir>/src/domains/purchases/$1',
    '^@/purchase-receipts/(.*)$': '<rootDir>/src/domains/purchase-receipts/$1',
    '^@/purchase-returns/(.*)$': '<rootDir>/src/domains/purchase-returns/$1',
    '^@/orders/(.*)$': '<rootDir>/src/domains/orders/$1',
    '^@/shipments/(.*)$': '<rootDir>/src/domains/shipments/$1',
    '^@/sale-returns/(.*)$': '<rootDir>/src/domains/sale-returns/$1',
    '^@/transfers/(.*)$': '<rootDir>/src/domains/transfers/$1',
    '^@/adjustments/(.*)$': '<rootDir>/src/domains/adjustments/$1',
    '^@/payments/(.*)$': '<rootDir>/src/domains/payments/$1',
    '^@/carts/(.*)$': '<rootDir>/src/domains/carts/$1',
    '^@/print-templates/(.*)$': '<rootDir>/src/domains/print-templates/$1',
    '^@/printer-configs/(.*)$': '<rootDir>/src/domains/printer-configs/$1',
    '^@/printers/(.*)$': '<rootDir>/src/domains/printers/$1',
    '^@/(.*)$': '<rootDir>/src/$1',
  },
  setupFilesAfterEnv: ['<rootDir>/test/setup.ts'],
};
